// Weapon definitions. Angles in degrees, speeds in m/s, ink cost in tank units.

export const WEAPONS = [
  {
    id: 'blaster',
    name: 'BLASTER',
    desc: 'Equilibrado',
    fireInterval: 0.15,
    damage: 26,
    pellets: 1,
    spread: 2.6,
    aimSpread: 0.7,
    fan: 0,
    speed: 44,
    straightTime: 0.42,
    inkCost: 1.5,
    splatRadius: 1.1,
    projectileSize: 0.17,
    trailEvery: 0.07,
    trailRadius: 0.6,
    recoil: 0.35,
    shake: 0.05,
    sound: 'blaster',
    botRange: 20,
  },
  {
    id: 'roller',
    name: 'ROLLER',
    desc: 'Corto alcance · Pinta el suelo',
    fireInterval: 0.7,
    damage: 34,
    pellets: 7,
    spread: 3,
    aimSpread: 2,
    fan: 44,
    speed: 23,
    straightTime: 0.2,
    inkCost: 7,
    splatRadius: 1.3,
    projectileSize: 0.26,
    trailEvery: 0,
    trailRadius: 0,
    recoil: 0.9,
    shake: 0.14,
    sound: 'roller',
    botRange: 7,
    roll: { inkPerSec: 8, width: 1.25, dps: 190, interval: 0.05 },
  },
  {
    id: 'splasher',
    name: 'SPLASHER',
    desc: 'Cadencia alta · Gasta mucha pintura',
    fireInterval: 0.07,
    damage: 9,
    pellets: 1,
    spread: 6.5,
    aimSpread: 3.2,
    fan: 0,
    speed: 38,
    straightTime: 0.33,
    inkCost: 1.05,
    splatRadius: 0.85,
    projectileSize: 0.12,
    trailEvery: 0.1,
    trailRadius: 0.45,
    recoil: 0.12,
    shake: 0.02,
    sound: 'splasher',
    botRange: 16,
  },
];
